name: Cypress API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install

      - name: Executa testes com Cypress
        run: npm run test:api

      - name: Gera relatório
        run: |
          npm run merge:reports
          npm run generate:report

      - name: Publica artefato do relatório
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome/html
